FROM debian:13

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN yes | apt-get install -y nano htop wget dialog iproute2 openssh-client sudo snapd curl iputils-ping
RUN echo 'root:root' | chpasswd
RUN printf '#!/bin/sh\nexit 0' > /usr/sbin/policy-rc.d
RUN yes | apt-get install -y systemd systemd-sysv dbus dbus-user-session
RUN printf "systemctl start systemd-logind" >> /etc/profile

ENTRYPOINT ["/sbin/init"]
